###
#
# Build site.
#

build:
  image: ruby:slim
  script:
    - apt-get install build-essential
    - gem install jekyll
    - jekyll build -d public
  artifacts:
    paths:
      - public
    expire_in: 1 day

