###
#
# Build site.
#

build:
  image: ruby:slim
  script:
    - apt-get update
    - apt-get install build-essential -y
    - gem install jekyll
    - jekyll build -d public
    - cp .fit-pages.yml public/
  artifacts:
    paths:
      - public
    expire_in: 1 day

